AllCops:
  TargetRubyVersion: 2.3

  DisplayCopNames: true

  Exclude:
    # autogenerate binstubs don't need linting
    - "bin/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: hash_rockets
